sonar.projectKey=todoapp-frontend
sonar.projectName=Frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.tsx, **/*.spec.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**, .next/**, out/**