stages:
  - build
  - test
  - quality

# Cache shared across all branch builds to speed up node_modules installation
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
  policy: pull-push

build_services:
  stage: build
  image: node:20-alpine
  parallel:
    matrix:
      # These must match your folder names exactly
      - SERVICE_DIR: ["auth-service", "todo-service", "todoapp-frontend"]
  script:
    - cd $SERVICE_DIR
    - echo "Installing dependencies for $SERVICE_DIR..."
    - npm i --legacy-peer-deps
    - echo "Running production build for $SERVICE_DIR..."
    - npm run build
    - echo "$SERVICE_DIR built successfully!"
  artifacts:
    # We store the build outputs so the 'Deploy' stage can use them later
    paths:
      - auth-service/dist/
      - todo-service/dist/
      - todoapp-frontend/.next/
      - "*/node_modules/"
    expire_in: 1 hour
  only:
    - main

run_tests:
  stage: test
  image: node:20-alpine
  parallel:
    matrix:
      - SERVICE_DIR: ["auth-service", "todo-service"]
  script:
    - cd $SERVICE_DIR
    # We don't need npm install because we use artifacts from the build stage
    - echo "Running tests for $SERVICE_DIR..."
    - npm test -- --watchAll=false --passWithNoTests --coverage  --handler=lcov
  only:
    - main

sonarqube_check:
  stage: quality
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  parallel:
    matrix:
      - SERVICE_DIR: ["auth-service", "todo-service", "todoapp-frontend"]
script: 
    - cd $SERVICE_DIR
    - sonar-scanner \
        -Dsonar.host.url=${SONAR_HOST_URL} \
        -Dsonar.login=${SONAR_TOKEN} \
        -Dsonar.organization=${SONAR_ORGANIZATION} \
        -Dsonar.qualitygate.wait=true